repos:
  - repo: https://github.com/econchick/interrogate
    rev: 237be78f9c6135fc1a620d211cdfdc5d3885082b
    hooks:
      - id: interrogate
        args: [--config=pyproject.toml]
        pass_filenames: true

  - repo: https://github.com/PyCQA/flake8
    rev: 5c52d752e64f210369b37654e7b26ce25e2266d6
    hooks:
      - id: flake8 # E***, W***, F***
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          - mccabe # C9**
          - pep8-naming # N8**

  - repo: https://github.com/pycqa/isort
    rev: 7de182933fd50e04a7c47cc8be75a6547754b19c
    hooks:
      - id: isort
        # args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/PyCQA/docformatter
    rev: 504107bdc4618f83a3378faac610e02cd62ef5f9
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --pre-summary-newline, --blank, --diff]

  - repo: https://github.com/psf/black
    rev: 8fe602b1fa91dc6db682d1dba79a8a7341597271
    hooks:
      - id: black
        args: [--line-length=79]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
